-- 险种管理初始数据 (去重后共34条)
-- 使用前请确认 jonlink_insurance_type 表已存在

INSERT INTO jonlink_insurance_type (type_name, type_code, sort, status, remark, create_by, create_time)
VALUES
('意外险', 'YWX', 1, '1', NULL, 'admin', NOW()),
('活动意外', 'HDYW', 2, '1', NULL, 'admin', NOW()),
('运动险', 'YDX', 3, '1', NULL, 'admin', NOW()),
('驾乘险', 'JCX', 4, '1', NULL, 'admin', NOW()),
('旅游险', 'LYX', 5, '1', NULL, 'admin', NOW()),
('百万医疗', 'BWYL', 6, '1', NULL, 'admin', NOW()),
('高风险意外', 'GFXYW', 7, '1', NULL, 'admin', NOW()),
('母婴人群', 'MYRQ', 8, '1', NULL, 'admin', NOW()),
('家庭意外', 'JTYW', 9, '1', NULL, 'admin', NOW()),
('少儿意外', 'SEYW', 10, '1', NULL, 'admin', NOW()),
('财产险', 'CCX', 11, '1', NULL, 'admin', NOW()),
('家财险', 'JCX2', 12, '1', NULL, 'admin', NOW()),
('网约车', 'WYC', 13, '1', NULL, 'admin', NOW()),
('成人意外', 'CRYW', 14, '1', NULL, 'admin', NOW()),
('学平险', 'XPX', 15, '1', NULL, 'admin', NOW()),
('摩托车', 'MTC', 16, '1', NULL, 'admin', NOW()),
('非机动车', 'FJDC', 17, '1', NULL, 'admin', NOW()),
('家政险', 'JZX', 18, '1', NULL, 'admin', NOW()),
('高保额意外', 'GBEYW', 19, '1', NULL, 'admin', NOW()),
('责任险', 'ZRX', 20, '1', NULL, 'admin', NOW()),
('医责险', 'YZX', 21, '1', NULL, 'admin', NOW()),
('老人意外', 'LRYW', 22, '1', NULL, 'admin', NOW()),
('明星意外', 'MXYW', 23, '1', NULL, 'admin', NOW()),
('工作意外', 'GZYW', 24, '1', NULL, 'admin', NOW()),
('医疗险', 'YLX', 25, '1', NULL, 'admin', NOW()),
('宠物险', 'CWX', 26, '1', NULL, 'admin', NOW()),
('雇主责任险', 'GZZRX', 27, '1', NULL, 'admin', NOW()),
('团体意外险', 'TTYW', 28, '1', NULL, 'admin', NOW()),
('个险', 'GX', 29, '1', NULL, 'admin', NOW()),
('公众责任险', 'GZZRX2', 30, '1', NULL, 'admin', NOW()),
('组织者责任险', 'ZZZRX', 31, '1', NULL, 'admin', NOW()),
('建工险', 'JGX', 32, '1', NULL, 'admin', NOW()),
('运动意外', 'YDYW', 33, '1', NULL, 'admin', NOW()),
('个意险', 'GYX', 34, '1', NULL, 'admin', NOW());
