-- 保险公司初始数据 (共43家)
-- 使用前请确认 jonlink_insurance_company 表已存在

INSERT INTO jonlink_insurance_company (company_name, company_code, status, remark, create_by, create_time)
VALUES
('中国人民财产保险股份有限公司', 'PICC', '1', '中资', 'admin', NOW()),
('中国大地财产保险股份有限公司', 'CCIC', '1', '中资', 'admin', NOW()),
('中华联合财产保险股份有限公司', 'CUIC', '1', '中资', 'admin', NOW()),
('中国太平洋财产保险股份有限公司', 'CPIC', '1', '中资', 'admin', NOW()),
('中国平安财产保险股份有限公司', 'PINGAN', '1', '中资', 'admin', NOW()),
('申能财产保险股份有限公司', 'SHENNENG', '1', '中资', 'admin', NOW()),
('中国人寿财产保险股份有限公司', 'CLIC', '1', '中资', 'admin', NOW()),
('太平财产保险有限公司', 'TPCC', '1', '中资', 'admin', NOW()),
('阳光财产保险股份有限公司', 'YANGGUANG', '1', '中资', 'admin', NOW()),
('华安财产保险股份有限公司', 'HUAAN', '1', '中资', 'admin', NOW()),
('永安财产保险股份有限公司', 'YONGAN', '1', '中资', 'admin', NOW()),
('中银保险有限公司', 'BOCINS', '1', '中资', 'admin', NOW()),
('亚太财产保险有限公司', 'APIC', '1', '中资', 'admin', NOW()),
('永诚财产保险股份有限公司', 'YONGCHENG', '1', '中资', 'admin', NOW()),
('都邦财产保险股份有限公司', 'DUBANG', '1', '中资', 'admin', NOW()),
('渤海财产保险股份有限公司', 'BOHAI', '1', '中资', 'admin', NOW()),
('华农财产保险股份有限公司', 'HUANONG', '1', '中资', 'admin', NOW()),
('安诚财产保险股份有限公司', 'ANCHENG', '1', '中资', 'admin', NOW()),
('鼎和财产保险股份有限公司', 'DINGHE', '1', '中资', 'admin', NOW()),
('中煤财产保险股份有限公司', 'ZHONGMEI', '1', '中资', 'admin', NOW()),
('英大泰和财产保险股份有限公司', 'YINGDATAIHE', '1', '中资', 'admin', NOW()),
('紫金财产保险股份有限公司', 'ZIJIN', '1', '中资', 'admin', NOW()),
('国任财产保险股份有限公司', 'GUOREN', '1', '中资', 'admin', NOW()),
('泰山财产保险股份有限公司', 'TAISHAN', '1', '中资', 'admin', NOW()),
('锦泰财产保险股份有限公司', 'JINTAI', '1', '中资', 'admin', NOW()),
('众诚汽车保险股份有限公司', 'ZHONGCHENG', '1', '中资', 'admin', NOW()),
('华泰财产保险有限公司', 'HUATAI', '1', '中资', 'admin', NOW()),
('长江财产保险股份有限公司', 'CHANGJIANG', '1', '中资', 'admin', NOW()),
('富德财产保险股份有限公司', 'FUDE', '1', '中资', 'admin', NOW()),
('北部湾财产保险股份有限公司', 'BEIBUWAN', '1', '中资', 'admin', NOW()),
('众安在线财产保险股份有限公司', 'ZHONGAN', '1', '中资', 'admin', NOW()),
('燕赵财产保险股份有限公司', 'YANZHAO', '1', '中资', 'admin', NOW()),
('恒邦财产保险股份有限公司', 'HENGBANG', '1', '中资', 'admin', NOW()),
('合众财产保险股份有限公司', 'HEZHONG', '1', '中资', 'admin', NOW()),
('中路财产保险股份有限公司', 'ZHONGLU', '1', '中资', 'admin', NOW()),
('泰康在线财产保险股份有限公司', 'TAIKANG', '1', '中资', 'admin', NOW()),
('珠峰财产保险股份有限公司', 'ZHUFENG', '1', '中资', 'admin', NOW()),
('黄河财产保险股份有限公司', 'HUANGHE', '1', '中资', 'admin', NOW()),
('太平科技保险股份有限公司', 'TPTECH', '1', '中资', 'admin', NOW()),
('大家财产保险有限责任公司', 'DAJIA', '1', '中资', 'admin', NOW()),
('史带财产保险股份有限公司', 'STARR', '1', '外资', 'admin', NOW()),
('安华农业保险股份有限公司', 'ANHUA', '1', '中资', 'admin', NOW()),
('美亚财产保险有限公司', 'AIG', '1', '外资', 'admin', NOW()),
('三星财产保险（中国）有限公司', 'SAMSUNG', '1', '外资', 'admin', NOW()),
('安盟财产保险有限公司', 'AMAG', '1', '外资', 'admin', NOW());
